// Package event defines the integration events the service publishes and
// the envelope that wraps them. Type and version are fixed by each
// constructor; callers only supply identifiers and data.
package event

import (
	"fmt"
	"time"

	"github.com/fiorellizz/backend-challenge-go/internal/domain/errs"
	"github.com/fiorellizz/backend-challenge-go/internal/domain/money"
)

// Event types and their current schema versions.
const (
	TypeWagerTransactionProcessed        = "WagerTransactionProcessed"
	TypeWagerTransactionRejected         = "WagerTransactionRejected"
	TypeWalletBalanceChanged             = "WalletBalanceChanged"
	TypeWagerTransactionPendingReference = "WagerTransactionPendingReference"

	AggregateWagerTransaction = "WagerTransaction"
	AggregateWallet           = "Wallet"

	schemaVersion = 1
)

// Envelope is the wire format. Data is one of the typed payloads below;
// money renders as {"amount","currency"} and timestamps as RFC 3339 UTC.
type Envelope struct {
	EventID       string    `json:"eventId"`
	EventType     string    `json:"eventType"`
	AggregateType string    `json:"aggregateType"`
	AggregateID   string    `json:"aggregateId"`
	CorrelationID string    `json:"correlationId"`
	CausationID   string    `json:"causationId,omitempty"`
	OccurredAt    time.Time `json:"occurredAt"`
	Version       int       `json:"version"`
	Data          any       `json:"data"`
}

// Meta carries the identifiers every event needs. EventID is generated by
// the caller and must stay the same across republications.
type Meta struct {
	EventID       string
	CorrelationID string
	CausationID   string
	OccurredAt    time.Time
}

// WagerTransactionProcessed is emitted when an operation completes,
// including LOSS and the internal OPENING. Provider fields are empty for
// internal origins.
type WagerTransactionProcessed struct {
	TransactionID         string      `json:"transactionId"`
	ProviderID            string      `json:"providerId,omitempty"`
	ExternalTransactionID string      `json:"externalTransactionId,omitempty"`
	WalletID              string      `json:"walletId"`
	PlayerID              string      `json:"playerId"`
	RoundID               string      `json:"roundId,omitempty"`
	GameID                string      `json:"gameId,omitempty"`
	Kind                  string      `json:"kind"`
	Money                 money.Money `json:"money"`
	Balance               money.Money `json:"balance"`
	WalletVersion         int64       `json:"walletVersion"`
	ProcessedAt           time.Time   `json:"processedAt"`
}

// WagerTransactionRejected is emitted on a definitive business rejection.
type WagerTransactionRejected struct {
	TransactionID         string      `json:"transactionId"`
	ProviderID            string      `json:"providerId"`
	ExternalTransactionID string      `json:"externalTransactionId"`
	WalletID              string      `json:"walletId"`
	PlayerID              string      `json:"playerId"`
	Kind                  string      `json:"kind"`
	Money                 money.Money `json:"money"`
	FailureCode           string      `json:"failureCode"`
	RejectedAt            time.Time   `json:"rejectedAt"`
}

// WalletBalanceChanged is emitted for every ledger entry.
type WalletBalanceChanged struct {
	WalletID      string      `json:"walletId"`
	TransactionID string      `json:"transactionId"`
	Direction     string      `json:"direction"`
	Money         money.Money `json:"money"`
	BalanceBefore money.Money `json:"balanceBefore"`
	BalanceAfter  money.Money `json:"balanceAfter"`
	WalletVersion int64       `json:"walletVersion"`
}

// WagerTransactionPendingReference is emitted when a reversal is parked
// waiting for the transaction it references.
type WagerTransactionPendingReference struct {
	TransactionID                  string    `json:"transactionId"`
	ProviderID                     string    `json:"providerId"`
	ExternalTransactionID          string    `json:"externalTransactionId"`
	WalletID                       string    `json:"walletId"`
	Kind                           string    `json:"kind"`
	ReferenceExternalTransactionID string    `json:"referenceExternalTransactionId"`
	NextAttemptAt                  time.Time `json:"nextAttemptAt"`
	DeadlineAt                     time.Time `json:"deadlineAt"`
}

// NewWagerTransactionProcessed wraps the payload; the aggregate is the transaction.
func NewWagerTransactionProcessed(m Meta, d WagerTransactionProcessed) (Envelope, error) {
	d.ProcessedAt = d.ProcessedAt.UTC()
	return wrap(m, TypeWagerTransactionProcessed, AggregateWagerTransaction, d.TransactionID, d)
}

// NewWagerTransactionRejected wraps the payload; the aggregate is the transaction.
func NewWagerTransactionRejected(m Meta, d WagerTransactionRejected) (Envelope, error) {
	d.RejectedAt = d.RejectedAt.UTC()
	return wrap(m, TypeWagerTransactionRejected, AggregateWagerTransaction, d.TransactionID, d)
}

// NewWalletBalanceChanged wraps the payload; the aggregate is the wallet.
func NewWalletBalanceChanged(m Meta, d WalletBalanceChanged) (Envelope, error) {
	return wrap(m, TypeWalletBalanceChanged, AggregateWallet, d.WalletID, d)
}

// NewWagerTransactionPendingReference wraps the payload; the aggregate is the transaction.
func NewWagerTransactionPendingReference(m Meta, d WagerTransactionPendingReference) (Envelope, error) {
	d.NextAttemptAt = d.NextAttemptAt.UTC()
	d.DeadlineAt = d.DeadlineAt.UTC()
	return wrap(m, TypeWagerTransactionPendingReference, AggregateWagerTransaction, d.TransactionID, d)
}

func wrap(m Meta, eventType, aggregateType, aggregateID string, data any) (Envelope, error) {
	if m.EventID == "" {
		return Envelope{}, fmt.Errorf("%w: event without id", errs.ErrValidation)
	}
	if m.CorrelationID == "" {
		return Envelope{}, fmt.Errorf("%w: event without correlation id", errs.ErrValidation)
	}
	if m.OccurredAt.IsZero() {
		return Envelope{}, fmt.Errorf("%w: event without occurrence time", errs.ErrValidation)
	}
	if aggregateID == "" {
		return Envelope{}, fmt.Errorf("%w: %s without aggregate id", errs.ErrValidation, eventType)
	}
	return Envelope{
		EventID:       m.EventID,
		EventType:     eventType,
		AggregateType: aggregateType,
		AggregateID:   aggregateID,
		CorrelationID: m.CorrelationID,
		CausationID:   m.CausationID,
		OccurredAt:    m.OccurredAt.UTC(),
		Version:       schemaVersion,
		Data:          data,
	}, nil
}
