// Package wallet holds the financial aggregate root. A Wallet owns its
// balance: the only way to change it is through Debit, Credit or the one-off
// OpeningCredit, each of which produces the ledger entry that must be
// persisted in the same SQL transaction as the new balance.
package wallet

import (
	"errors"
	"fmt"
	"time"

	"github.com/fiorellizz/backend-challenge-go/internal/domain/errs"
	"github.com/fiorellizz/backend-challenge-go/internal/domain/id"
	"github.com/fiorellizz/backend-challenge-go/internal/domain/money"
)

var (
	// ErrInsufficientBalance is a business rejection: the debit would leave
	// the balance below zero. It is not a validation error, the input was
	// well formed.
	ErrInsufficientBalance = errors.New("insufficient balance")

	// ErrAlreadyOpened is returned when an opening credit is applied to a
	// wallet that was not just created, e.g. a rehydrated one.
	ErrAlreadyOpened = fmt.Errorf("%w: wallet already opened", errs.ErrConflict)
)

// Wallet is the aggregate root. Balance changes bump the version; the
// version is the optimistic-concurrency token exposed to clients and is
// also what WalletBalanceChanged events carry.
type Wallet struct {
	id        id.WalletID
	playerID  id.PlayerID
	currency  money.Currency
	balance   money.Money
	version   int64
	createdAt time.Time
	updatedAt time.Time

	// fresh is true only between New and the first persisted state. It lets
	// the opening credit run once and never on a rehydrated wallet.
	fresh bool
}

// Snapshot is the plain representation used to persist and rehydrate a
// wallet. It carries no behaviour.
type Snapshot struct {
	ID        id.WalletID
	PlayerID  id.PlayerID
	Currency  money.Currency
	Balance   money.Money
	Version   int64
	CreatedAt time.Time
	UpdatedAt time.Time
}

// Movement describes one balance change requested from the wallet. The
// identifiers are generated by the caller so the domain stays free of
// random sources.
type Movement struct {
	EntryID       id.LedgerEntryID
	TransactionID id.TransactionID
	Amount        money.Money
	At            time.Time
}

// New creates an empty wallet at version 1.
func New(walletID id.WalletID, playerID id.PlayerID, currency money.Currency, now time.Time) (*Wallet, error) {
	zero, err := money.Zero(currency)
	if err != nil {
		return nil, err
	}
	w, err := Rehydrate(Snapshot{
		ID: walletID, PlayerID: playerID, Currency: currency,
		Balance: zero, Version: 1, CreatedAt: now, UpdatedAt: now,
	})
	if err != nil {
		return nil, err
	}
	w.fresh = true
	return w, nil
}

// Rehydrate rebuilds a wallet from persisted state. It validates the
// invariants but replays nothing: no ledger entry, no version bump.
func Rehydrate(s Snapshot) (*Wallet, error) {
	if err := s.ID.Validate(); err != nil {
		return nil, err
	}
	if err := s.PlayerID.Validate(); err != nil {
		return nil, err
	}
	if err := s.Balance.Validate(); err != nil {
		return nil, err
	}
	if s.Balance.Currency() != s.Currency {
		return nil, fmt.Errorf("%w: balance is %s but wallet currency is %s",
			money.ErrCurrencyMismatch, s.Balance.Currency(), s.Currency)
	}
	if s.Balance.IsNegative() {
		return nil, fmt.Errorf("%w: negative balance %s", errs.ErrValidation, s.Balance)
	}
	if s.Version < 1 {
		return nil, fmt.Errorf("%w: version must be >= 1, got %d", errs.ErrValidation, s.Version)
	}
	if s.CreatedAt.IsZero() || s.UpdatedAt.IsZero() {
		return nil, fmt.Errorf("%w: wallet without timestamps", errs.ErrValidation)
	}
	return &Wallet{
		id: s.ID, playerID: s.PlayerID, currency: s.Currency, balance: s.Balance,
		version: s.Version, createdAt: s.CreatedAt, updatedAt: s.UpdatedAt,
	}, nil
}

// Snapshot returns the persistable state.
func (w *Wallet) Snapshot() Snapshot {
	return Snapshot{
		ID: w.id, PlayerID: w.playerID, Currency: w.currency, Balance: w.balance,
		Version: w.version, CreatedAt: w.createdAt, UpdatedAt: w.updatedAt,
	}
}

func (w *Wallet) ID() id.WalletID          { return w.id }
func (w *Wallet) PlayerID() id.PlayerID    { return w.playerID }
func (w *Wallet) Currency() money.Currency { return w.currency }
func (w *Wallet) Balance() money.Money     { return w.balance }
func (w *Wallet) Version() int64           { return w.version }
func (w *Wallet) CreatedAt() time.Time     { return w.createdAt }
func (w *Wallet) UpdatedAt() time.Time     { return w.updatedAt }

// OpeningCredit applies the initial balance of a freshly created wallet. It
// is the one credit that keeps the version at 1, and it can run only once.
func (w *Wallet) OpeningCredit(m Movement) (LedgerEntry, error) {
	if !w.fresh {
		return LedgerEntry{}, ErrAlreadyOpened
	}
	entry, err := w.apply(m, Credit)
	if err != nil {
		return LedgerEntry{}, err
	}
	w.fresh = false
	return entry, nil
}

// Credit adds funds and bumps the version.
func (w *Wallet) Credit(m Movement) (LedgerEntry, error) {
	entry, err := w.apply(m, Credit)
	if err != nil {
		return LedgerEntry{}, err
	}
	w.version++
	return entry, nil
}

// Debit removes funds and bumps the version. It fails with
// ErrInsufficientBalance when the balance would go below zero.
func (w *Wallet) Debit(m Movement) (LedgerEntry, error) {
	entry, err := w.apply(m, Debit)
	if err != nil {
		return LedgerEntry{}, err
	}
	w.version++
	return entry, nil
}

// apply validates the movement, computes the new balance, builds the ledger
// entry and only then mutates the wallet. Any failure leaves it untouched.
func (w *Wallet) apply(m Movement, dir Direction) (LedgerEntry, error) {
	if err := m.Amount.Validate(); err != nil {
		return LedgerEntry{}, err
	}
	if !m.Amount.IsPositive() {
		return LedgerEntry{}, fmt.Errorf("%w: movement amount must be positive, got %s", errs.ErrValidation, m.Amount)
	}
	if m.Amount.Currency() != w.currency {
		return LedgerEntry{}, fmt.Errorf("%w: movement in %s on a %s wallet",
			money.ErrCurrencyMismatch, m.Amount.Currency(), w.currency)
	}

	var after money.Money
	var err error
	if dir == Credit {
		after, err = w.balance.Add(m.Amount)
	} else {
		after, err = w.balance.Sub(m.Amount)
	}
	if err != nil {
		return LedgerEntry{}, err
	}
	if after.IsNegative() {
		return LedgerEntry{}, fmt.Errorf("%w: balance %s, debit %s", ErrInsufficientBalance, w.balance, m.Amount)
	}

	entry, err := NewLedgerEntry(LedgerEntryParams{
		ID: m.EntryID, WalletID: w.id, TransactionID: m.TransactionID, Direction: dir,
		Amount: m.Amount, BalanceBefore: w.balance, BalanceAfter: after, CreatedAt: m.At,
	})
	if err != nil {
		return LedgerEntry{}, err
	}

	w.balance = after
	w.updatedAt = m.At
	return entry, nil
}
